FROM node:alpine

#bash is used to run npm test inside the container
RUN apk update && apk upgrade && apk --update add bash && rm -rf /var/cache/apk/*

WORKDIR /src
ADD . .

RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
    && apk del .gyp

EXPOSE 5000

CMD ["node", "app.js"]